name: test_server_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  agora_rtc_engine: ^6.3.2
  cached_network_image: ^3.4.1
  country_pickers: ^3.0.1
  dartz: ^0.10.1
  dio: ^5.7.0
  emoji_picker_flutter: ^3.1.0
  equatable: ^2.0.5
  file_picker: ^8.1.3
  firebase_app_check: ^0.3.1+5
  firebase_core: ^3.7.0
  firebase_storage: ^12.3.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.6
  flutter_contacts: ^1.1.9+2
  flutter_pin_code_fields: ^2.2.0
  flutter_sound: ^9.17.0
  flutter_story_view: ^0.0.4
  fluttertoast: ^8.2.8
  get_it: ^8.0.2
  get_time_ago: ^2.0.0
  giphy_picker: ^3.0.2
  http: ^1.2.2
  http_parser: ^4.0.2
  image_picker: ^1.1.2
  internet_connection_checker: ^1.0.0+1
  intl: ^0.19.0
  json_annotation: ^4.9.0
  just_audio: ^0.9.42
  mime: ^2.0.0
  path_provider: ^2.1.5
  permission_handler: ^11.3.1
  shared_preferences: ^2.3.3
  socket_io_client: ^3.0.1
  swipe_to: ^1.0.6
  uuid: ^4.5.1
  video_player: ^2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  test: ^1.25.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  assets:
    - assets/